# -*- coding: utf-8 -*-

import hr_employee
import sanction_type
import qual_type
import medical_type
import hr_employee_sanction
import hr_employee_decoration
import hr_employee_decoration_type
import hr_employee_branche
import hr_employee_note
import hr_employee_last_job
import hr_employee_formation_module
import hr_employee_formation
import hr_employee_qualification
import hr_employee_medical_ticket
import hr_employee_children
import hr_holidays_status_type
import hr_holidays_status
import hr_replacement
import hr_holidays

import hr_holiday_job
import hr_job
import aptitude_type
import hr_applicant_aptitude
import hr_employee_aptitude
import hr_job_aptitude
import hr_applicant_formation
import hr_job_formation
import institute
import hr_job_qualification
import hr_applicant_qualification
import hr_task_categ
import hr_employee_task
import payment_mode
import payment_term
