# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !

# from osv import fields
from openerp import api, exceptions, fields, models

class HrEmployeeSanction(models.Model):
    """gestion des sanctions"""
    _name = 'hr.employee.sanction'
    _description = "Employee sanction"
    
    motif = fields.char(string='Motif', size=64)
    date = fields.date(string='Date')
    date_interview = fields.datetime(string='Date entretien')
    date_start = fields.date(string='Date debut sanction')
    date_end = fields.date(string='Date fin sanction')
    name = fields.many2one(comodel_name = 'hr.employee', string='Salarie')
    type = fields.many2one(comodel_name = 'sanction.type', string='Type de Sanction')
    description = fields.text(string='Commentaires')
    suite = fields.boolean(string='Avec suite')

hr_employee_sanction()
